# Project: Projecto
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Programacion.o Padre.o Matematicas.o Fisica.o Curso.o Alumno.o
LINKOBJ  = main.o Programacion.o Padre.o Matematicas.o Fisica.o Curso.o Alumno.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Projecto.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Programacion.o: Programacion.cpp
	$(CPP) -c Programacion.cpp -o Programacion.o $(CXXFLAGS)

Padre.o: Padre.cpp
	$(CPP) -c Padre.cpp -o Padre.o $(CXXFLAGS)

Matematicas.o: Matematicas.cpp
	$(CPP) -c Matematicas.cpp -o Matematicas.o $(CXXFLAGS)

Fisica.o: Fisica.cpp
	$(CPP) -c Fisica.cpp -o Fisica.o $(CXXFLAGS)

Curso.o: Curso.cpp
	$(CPP) -c Curso.cpp -o Curso.o $(CXXFLAGS)

Alumno.o: Alumno.cpp
	$(CPP) -c Alumno.cpp -o Alumno.o $(CXXFLAGS)
